### PR TITLE
add gpg signatures to downloads

### PR DESCRIPTION
**Pull request by MartinNowak**
- add gpg_keys page
- add download of d keyring
- link to gpg_keys from download page
- show sig download button only on hover

### CODE REVIEW

**Comment by CyberShadow** [comment]
win32.mak too please?

**Comment by MartinNowak** [comment]
See https://dlang.dawg.eu/download.html and https://dlang.dawg.eu/gpg_keys.html.

**Comment by MartinNowak** [comment]
I thought we agree on dropping that, but OK.

**Comment by CyberShadow** [comment]
The on-hover button shifts other buttons around. Not good.

On-hover effects should never move other things around.

**Comment by MartinNowak** [comment]
Update for win32.mak

**Comment by CyberShadow** [comment]
Maybe put the sig button under the main button?

**Comment by MartinNowak** [comment]
Yes, makes the buttons pretty busy.

> Maybe put the sig button under the main button?

Can try that, will be difficult to align, and adds a lot of noise.

**Comment by CyberShadow** [comment]
> Can try that, will be difficult to align, and adds a lot of noise.

I think I know how to do it without these problems.

**Comment by MartinNowak** [comment]
That's really ugly.
sig

**Comment by MartinNowak** [comment]
Well not that terrible, but I hope you have better idea.

**Comment by CyberShadow** [comment]
https://github.com/D-Programming-Language/dlang.org/pull/939

wamp is acting up so can't put up a live preview ATM.

**Pull request merged**
