### PR TITLE
Runnable examples: Connect directly to dpaste.dzfl.pl, skiping the pr…

### PR DESCRIPTION
**Pull request by nazriel**
…oxy written in PHP. + Use JSON instead of XML + add some debug info when response fails for some reason

@MartinNowak: as we discussed before, please merge ASAP.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Will deploy it when I get home.

**Comment by nazriel** [comment]
@MartinNowak sure, thanks!

**Comment by MartinNowak** [comment]
done

**Comment by nazriel** [comment]
@MartinNowak nice, it works :+1:

**Pull request merged**
