### PR TITLE
Ivan Smirnov's redesign

### PR DESCRIPTION
**Pull request by aG0aep6G**
Forum thread: http://forum.dlang.org/post/n6pdes$1upn$1@digitalmars.com

The last commit is the actual redesign. The others are independent small fixes. I can extract them and make individual pull requests if needed.

### CODE REVIEW

**Comment by aG0aep6G** [comment]
I made the Twitter widget from a new account. You may want to recreate it from another one, not leaving control over it in (relatively) untrusted hands. It's a "search" widget with these settings:
[snapshot](https://cloud.githubusercontent.com/assets/9287500/12222256/662c7204-b7b7-11e5-8333-7f9c8319ecdb.png).

**Comment by andralex** [comment]
It's a historical moment!

**Comment by CyberShadow** [comment]
Um, this is great work and all, but... uh, code review?

@andralex For any PR except the most trivial ones, we leave them open for 24 hours to allow everyone to check the diffs. This is anything but a trivial one. Please don't do this in the future.

**Comment by 9il** [comment]
I like unexpected merges)

**Comment by andralex** [comment]
@CyberShadow you're right. https://github.com/D-Programming-Language/dlang.org/pull/1189

**Pull request merged**
