### PR TITLE
add many anchors

### PR DESCRIPTION
**Pull request by BBasile**
I find that a lot of anchors are missing. It happened several time that I'd like to share a link to a particular section of dlang.org but the anchor was missing.

Half of the pages are done. waiting for approval for this to continue...maybe all these H2 & H3 are not anchored by purpose ?

### CODE REVIEW

**Comment by aG0aep6G** [comment]
What happened here?

**Comment by BBasile** [comment]
test failure

**Comment by aG0aep6G** [comment]
> test failure

From adding a bunch of anchors?? Do you know how to fix it, or if it's even related to your changes? I hope you don't give up on this just because the documentation tester has one of its moments.

**Comment by BBasile** [comment]
The test seems ok now. If people at dlang agree with the principle I'll finish the remaining half.

**Comment by BBasile** [comment]
done and green.

**Comment by BBasile** [comment]
If i want to give a link to  http://dlang.org/template.html, Template Constraints

I say: got to 

http://dlang.org/template.html#nested-templates

and scroll a bit...

**Pull request closed without merging**
