### PR TITLE
Update predefined versions to include FreeStanding.

### PR DESCRIPTION
**Pull request by ibuclaw**
Frontend compiler PR here: https://github.com/D-Programming-Language/dmd/pull/4367

### CODE REVIEW

**Comment by WalterBright** [comment]
Use `FreeStanding` instead.

**Comment by andralex** [comment]
yes please - it's a consecrated term

**Comment by ibuclaw** [comment]
OK, I'll give in and agree for the current time being.

**Comment by ibuclaw** [comment]
Any last requests before the 'But I wanted BareMetal' argument?

**Comment by JinShil** [comment]
LGTM and uses a term I'm already familiar with.

**Pull request merged**
