### PR TITLE
Fix spurious newlines after macro definitions

### PR DESCRIPTION
**Pull request by andralex**
See http://forum.dlang.org/post/mailman.4394.1420833627.9932.digitalmars-d@puremagic.com

### CODE REVIEW

**Comment by andralex** [comment]
cc @MartinNowak

**Comment by andralex** [comment]
Don't review yet, let me fix the issue in all .ddoc files.

**Comment by andralex** [comment]
Urgh, I pushed more to that branch and now I cannot reopen. How do I reopen now?

**Comment by jacob-carlborg** [comment]
If you have permission to merge a pull request you should have a button labeled "Reopen pull request" next to the comment button at the bottom of the page.

**Comment by jacob-carlborg** [comment]
Could there be a problem that the push was made when the pull request was closed?

**Pull request closed without merging**
