### PR TITLE
Made menus narrower to save screen real estate

### PR DESCRIPTION
**Pull request by JinShil**
narrow_menu

### CODE REVIEW

**Comment by andralex** [comment]
did you try with the stdlib menus? Some names there get pretty long

**Comment by CyberShadow** [comment]
Not sure about this, narrower = smaller click target, more difficult to navigate. We have literally nothing else in that vertical space, so all space under the menu is wasted. How about a dynamic CSS rule based on the display height?

**Comment by JinShil** [comment]
> did you try with the stdlib menus? Some names there get pretty long

Yes, it looks fine for me.

**Comment by andralex** [comment]
@CyberShadow: I think I was wrong, that doesn't reduce the click target, only the padding.

**Comment by JinShil** [comment]
> Not sure about this, narrower = smaller click target, more difficult to navigate. We have literally nothing else in that vertical space, so all space under the menu is wasted. How about a dynamic CSS rule based on the display height?

The library reference requires too much scrolling, so I though the narrow menus would be a good idea.

**Comment by CyberShadow** [comment]
> The library reference requires too much scrolling, so I though the narrow menus would be a good idea.

That's true. But why not just apply this to the library reference?

**Comment by JinShil** [comment]
> That's true. But why not just apply this to the library reference?

I think that would look weird because the menus would be inconsistent with the rest of the site.

**Comment by CyberShadow** [comment]
There is already some inconsistency, the module list uses a monotype font.

**Comment by andralex** [comment]
Oh oh... s/narrower/shorter/ and I understood everything

**Pull request merged**
