### PR TITLE
improve notices

### PR DESCRIPTION
**Pull request by MartinNowak**
- square blocks with less shadow
- turn whole block into clickable link
- use dark background + accent color

### CODE REVIEW

**Comment by MartinNowak** [comment]
notice

**Comment by CyberShadow** [comment]
That looks very jarring on my screen at least.

**Comment by MartinNowak** [comment]
https://dlang.dawg.eu/

**Comment by MartinNowak** [comment]
> That looks very jarring on my screen at least.

It just looks about right on mine and it's also supposed to be noticed.

**Comment by MartinNowak** [comment]
Also the first time, that the website has a clear center of focus.

**Comment by MartinNowak** [comment]
Two alternatives.
`white`
notice_white
[`Red A700 (#D50000)`](http://www.google.com/design/spec/style/color.html#color-color-palette)
notice_red_a700

**Comment by CyberShadow** [comment]
White is much nicer.

Also, I just remembered that red-on-black is almost unreadable for people with protanopia, so we should avoid that.

**Comment by CyberShadow** [comment]
#950

**Pull request merged**
