### PR TITLE
Issue 14579 - [SPEC] No specification on modifiers in TypeDelegate symbols

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14579

### CODE REVIEW

**Comment by JinShil** [comment]
I can't vouch for the technical accuracy, but everything else looks good.

**Comment by JinShil** [comment]
@Hackerpilot, you're our grammar expert, right?  Would you mind doing a review?

**Comment by Hackerpilot** [comment]
This is the change to the documentation for the symbol name mangling specification, not the language itself. I don't know if this is correct or not.

**Comment by ibuclaw** [comment]
This is how my grammar works in the GNU Libiberty demangler (used in Binutils and GDB).

**Pull request merged**
