### PR TITLE
remove underlines from links

### PR DESCRIPTION
**Pull request by aG0aep6G**
Before/after:
iconscreenshot1

### CODE REVIEW

**Comment by CyberShadow** [comment]
:-1: Links should stay underlined, IMHO. This becomes even more ambiguous for links inside text that has other colors, such as symbol listings, or cross references in Ddox. This also clashes with D keywords in syntax-highlighted code.

**Comment by aG0aep6G** [comment]
> This becomes even more ambiguous for links inside text that has other colors, such as symbol listings, or cross references in Ddox.

I'd say they should be blue, too.

> This also clashes with D keywords in syntax-highlighted code.

And those not blue.

If it's acceptable then, I'd try and change those accordingly.

**Comment by CyberShadow** [comment]
You're welcome to try, although I can't imagine a variation of your proposal which I would consider a positive change. IMHO, non-underlined links are a gimmick which harms usability more than it improves style. But if you post your results to the forum and people will like it, it'll likely go in.

**Comment by andralex** [comment]
I personally like the un-underlined jump links. Too many underlined words together - underlining is just noise. Also, it's rather obvious that they're supposed to be clicked on, otherwise why clump them together.

@aG0aep6G: Discuss on the forum. I'll fight for ya.

**Comment by CyberShadow** [comment]
I don't mind as much removing underlining from indexes and other places where almost everything is a link (as we already do with navigation), but it should not be done everywhere. Doing so has accessibility consequences (e.g. it makes it difficult for colorblind users to discern links).

**Comment by andralex** [comment]
Oh wait I missed that. Nonono, underlining should be disabled ONLY in the table shown in the screenshot. @aG0aep6G that can be done with a CSS class, could you please do that?

**Comment by aG0aep6G** [comment]
> Doing so has accessibility consequences (e.g. it makes it difficult for colorblind users to discern links).

That's a really good point.

> I personally like the un-underlined jump links.
[...]
> could you please do that?

I'm not sure it's a good idea. Like CyberShadow says, "it would be inconsistent to do it selectively in the main content". But here it goes: #843

**Comment by andralex** [comment]
nice work in #843 - closing this now

**Pull request closed without merging**
