### PR TITLE
Fix for issue 13624 (Part 2)

### PR DESCRIPTION
**Pull request by JackStouffer**
automatic replacement of hardware tabs with four spaces

### CODE REVIEW

**Comment by JackStouffer** [comment]
Ping. This change is trivial.

**Comment by CyberShadow** [comment]
Why is this a separate PR?

**Comment by JackStouffer** [comment]
People keep complaining about whitespace changes in PRs that don't need them.

**Comment by CyberShadow** [comment]
Grr, I disagree with that. Those are the people too lazy to click on individual commits. Oh well.

**Pull request merged**
