### PR TITLE
fix Issue 8846 - Specs for Inline Assembler don't include cmpxchg16b

### PR DESCRIPTION
**Pull request by WalterBright**
https://issues.dlang.org/show_bug.cgi?id=8846

### CODE REVIEW

**Comment by aG0aep6G** [comment]
Those empty cells in the middle of the table don't look nice.

**Comment by WalterBright** [comment]
Rewriting the whole table makes the diffs look bad.

**Comment by andralex** [comment]
Not sure what the matter here is. @WalterBright please just add the entries and call it a day?

**Comment by WalterBright** [comment]
I did just add the entries. The issue is the table is very large, and inserting a couple entries in the middle means redoing the entire rest of the table, resulting in large rather gratuitous diffs. So I inserted a couple blanks to avoid this.

**Comment by andralex** [comment]
I'll merge this as an improvement and build more on top of it if needed.

**Pull request merged**
