### PR TITLE
Grammar change for D-Programming-Language/dmd#5363

### PR DESCRIPTION
**Pull request by Hackerpilot**
D-Programming-Language/dmd#5363

### CODE REVIEW

**Comment by 9rnsr** [comment]
[StaticAssert](http://dlang.org/spec/grammar#StaticAssert
 needs also to be fixed.

**Comment by Hackerpilot** [comment]
Done.

**Comment by 9rnsr** [comment]
`expression.dd` is not sync with `grammar.dd`.

**Comment by Hackerpilot** [comment]
What do you mean?

**Comment by 9rnsr** [comment]
Hmm, sorry I've oversight `version.dd` change... LGTM!

**Pull request merged**
