### PR TITLE
add "make ... all" hint for rebuilding changes

### PR DESCRIPTION
**Pull request by zachthemystic**
I finally found how to do it at the top of the makefile, but better to say it here too.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Isn't `all` the default target?

Why is there a merge commit in your commit list?

**Comment by zachthemystic** [comment]
Look, I'm not a make expert. I used what the tutorial said. At the top of the make file:
```
# Makefile to build the entire dlang.org website
#
# To run:
#
# make -f posix.mak all
```
This isn't in CONTRIBUTING.md though. I do think it's clearer, for new people to learn about make. For experienced people, they would know anyway, right?

**Comment by zachthemystic** [comment]
--> Why is there a merge commit in your commit list?

I'm not good at git either!

**Comment by zachthemystic** [comment]
Closed. New pull: 
https://github.com/D-Programming-Language/dlang.org/pull/879

**Comment by andralex** [comment]
This is #879 :).

@zachthemystic thanks for your contributions. I suggest you get together with one of our git experts on IRC so they walk you through how it's done. It was a pain for me in the beginning, too. Don't get discouraged!

**Comment by CyberShadow** [comment]
New pull is https://github.com/D-Programming-Language/dlang.org/pull/880

**Pull request closed without merging**
