### PR TITLE
Issue 12803 - __traits(getFunctionAttributes) is not documented

### PR DESCRIPTION
**Pull request by nomad-software**
getFunctionAttributes is only currently missing from the grammar page. I notice another missing there too so i also added it.

Bugzilla: https://issues.dlang.org/show_bug.cgi?id=12803

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by CyberShadow** [comment]
Is `getPointerBitmap` part of the language? Sounds implementation-specific...

**Comment by CyberShadow** [comment]
Well, it's listed on http://dlang.org/traits.html so I guess it is.

**Comment by CyberShadow** [comment]
The bug report said that it is not listed on the traits page, but someone had already added it since then.

**Pull request merged**
