### PR TITLE
provide input for examples

### PR DESCRIPTION
**Pull request by MartinNowak**
- also add pow (^^) to the rpn calculator

### CODE REVIEW

**Comment by CyberShadow** [comment]
https://github.com/D-Programming-Language/dlang.org/pull/1098 ?

**Comment by MartinNowak** [comment]
Updated @CyberShadow

**Comment by CyberShadow** [comment]
Too bad the "Run" button doesn't appear on the autotester, because it would involve a cross-origin request...

**Comment by nazriel** [comment]
@CyberShadow I guess we can allow auto-tester URL for cross-origin?

**Comment by CyberShadow** [comment]
I guess? Just keep in mind that anyone can create a PR...

**Comment by nazriel** [comment]
Hmm, not sure if they can do any more harm than just using dpaste.dzfl.pl ?
Although you may be right

**Pull request merged**
