### PR TITLE
add local jump ref to bugzilla changelog

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Will change the changelog tool to always emit those.

**Comment by CyberShadow** [comment]
http://dtest.thecybershadow.net/artifact/website-b8dee3087e4626d45c91b205e04d72bb045b8b21-edf92cc6544ac4277d27d034a279d438/web/changelog.html

That link looks wrong. It's not styled like any text around it.

**Comment by MartinNowak** [comment]
But it's the same as for 2.068.0 and the others.
http://dtest.thecybershadow.net/artifact/website-b8dee3087e4626d45c91b205e04d72bb045b8b21-edf92cc6544ac4277d27d034a279d438/web/changelog.html#list2068

**Comment by CyberShadow** [comment]
You're right. I guess it jumps at you with that one list item.

No other comments, merge if done.

**Pull request merged**
