### PR TITLE
Fix typo in operatoroverloading.dd

### PR DESCRIPTION
**Pull request by ZombineDev**

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:white_check_mark:

**Comment by schuetzm** [comment]
s/Rewritting/Rewriting/

**Comment by andralex** [comment]
thx - also appreciate the OKs from others. I'll pull and fix the typo right after.

**Comment by andralex** [comment]
@Hackerpilot, @schuetzm you now have rights to pull. Welcome to the club! :o)

**Pull request merged**
