### PR TITLE
add "make all" hint to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by zachthemystic**
Redone. New pull.

### CODE REVIEW

**Comment by CyberShadow** [comment]
... Why are there two commits in your commit ilst?

But seriously, that is just a nitpick. It's not *the* reason for why the previous pull did not get merged, if such a reason even exists other than enough people approving the change.

As for the change, as minor as it is, it is a little suspicious. Building the `all` target will not only rebuild things that have already been built, but potentially also build things which have not been built yet. The same command that worked for the first build *should* work again for rebuilding the same targets.

Maybe we should fix the makefile instead? Can you describe the problem first?

**Comment by zachthemystic** [comment]
My problem: I followed the instructions, then changed my files, and did "make -f posix.mak apidocs-prerelease" again, hoping it would rebuild the docs, but for some reason, it didn't because it thought they were up to date. I honestly don't know why it didn't work. "make all" and it did work, so I assumed that was what one was supposed to do. That's all I know.

**Comment by CyberShadow** [comment]
> then changed my files

Which files did you change? 

> apidocs-prerelease

This is the DDox build target. Were you working on DDox, or on Phobos but testing your changes using DDox?

**Comment by zachthemystic** [comment]
I wanted to build dlang.org. I had edited dlang.org/doc.ddoc, for example. What's the target for that?

**Comment by CyberShadow** [comment]
`html`, which is included in `all`.

**Comment by zachthemystic** [comment]
Okay, changed. Thanks for the guidance on this.

**Comment by CyberShadow** [comment]
OK, but isn't your addition now redundant? The README now says:

> To build the main site, run this:
> ```
> cd $R/dlang.org
> make -f posix.mak html
> ```
>
> ......................
> 
>To rebuild your dlang.org changes, use:
>```
>make -f posix.mak html
>```

**Comment by zachthemystic** [comment]
You're right. I just missed it. Sorry. Closing pull. Thanks for your patience.

**Comment by CyberShadow** [comment]
> You're right. I just missed it. Sorry.

No problem.

> Thanks for your patience.

You too.

**Pull request closed without merging**
