### PR TITLE
the big grey bar

### PR DESCRIPTION
**Pull request by aG0aep6G**
The less colorful sibling of #869.

Live version: http://ag0aep6g-dlang.rhcloud.com/variants/grey-oldlogo/

Forum sub thread: http://forum.dlang.org/post/mfcmljxeinnspctduioj@forum.dlang.org

Shoutout to @veelo for color suggestions!

###### Screenshots

wide:
screen shot 2015-01-29 at 00 29 09

narrow:
screen shot 2015-01-29 at 00 28 06

narrow with menu:
screen shot 2015-01-29 at 00 28 24

### CODE REVIEW

**Comment by MartinNowak** [comment]
Any comments on the implementation? Otherwise I'll merge this in a few hours.

**Comment by CyberShadow** [comment]
Implementation LGTM. The only noteworthy thing is the `body::before` trick, I hadn't heard about it before. As long as it works in major browsers, it should be fine.

**Comment by CyberShadow** [comment]
Looks like my SVG logo pull broke this. @aG0aep6G - please rebase?

**Comment by aG0aep6G** [comment]
rebased

**Comment by aG0aep6G** [comment]
Added a commit to match color with the svg logo.

**Comment by CyberShadow** [comment]
Thank you.

**Pull request merged**
