### PR TITLE
Issue 481 - Letting compiler determine length for fixed-length arrays

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=481

Corresponding compiler change: https://github.com/D-Programming-Language/dmd/pull/3615

### CODE REVIEW

**Comment by Hackerpilot** [comment]
The compiler change was merged, so the "Blocked" label needs to be removed.

**Comment by 9rnsr** [comment]
@Hackerpilot Thanks for the notification. I removed the 'Blocked' tag. Ready to merge.

**Comment by 9rnsr** [comment]
@MartinNowak I added a changelog note.

**Comment by MartinNowak** [comment]
> @MartinNowak I added a changelog note.

Thanks a lot Kenji.

**Pull request merged**
