### PR TITLE
changelog for 2.068.1

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
@CyberShadow you're DAutoTest doesn't rerun when I reopen a PR from the same branch.

**Comment by MartinNowak** [comment]
Please merge ASAP so I can build the release.

**Comment by CyberShadow** [comment]
I'm confused, I thought dot-releases were for fixing regressions, not adding new features?

**Comment by MartinNowak** [comment]
> I'm confused, I thought dot-releases were for fixing regressions, not adding new features?

It was a follow-up b/c 2.068.0 was missing those -profile=gc functions.

**Comment by CyberShadow** [comment]
Nit, the changelog looks like this:

### Library changes

1. (...)

### Library changes

1. (...)

("Library changes" repeats twice and both sections have a list with 1 item in them)

**Comment by MartinNowak** [comment]
> Nit, the changelog looks like this:

You're right, it's missing the `$(HR)` and the ref to the bugzilla list.
See #1093.

**Pull request merged**
