### PR TITLE
changelog entries for 2.068.0

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
> Let's use same order in the 'headers' list and 'descriptions'.

Yes, that was unintentional.

**Comment by 9rnsr** [comment]
Other than nitpicks, looks good.

**Comment by rainers** [comment]
> Is the object.di -> object.d change important? I'd just like to know why you list that change.

A user visible change is the renaming of field next to base in TypeInfo_Const. Some more small fixes are listed in https://github.com/D-Programming-Language/druntime/pull/1222

**Comment by 9rnsr** [comment]
@rainers Thanks, I understand.
@MartinNowak I think the changelog should notice such the actual effects to end users has introduced.

**Comment by MartinNowak** [comment]
Updated

**Comment by MartinNowak** [comment]
> Is the object.di -> object.d change important? I'd just like to know why you list that change.

I think it is, b/c there are often issues with correctly setting up import paths and or finding object.di.
Also a stale object.di would override the new object.d.

**Comment by MartinNowak** [comment]
wait

**Comment by MartinNowak** [comment]
OK
I added macros to reference PRs
The details of the object.d change shouldn't impact many people, so the PR ref should suffice.

**Comment by MartinNowak** [comment]
more phobos changelog entries

**Comment by MartinNowak** [comment]
Preview https://dlang.dawg.eu/changelog.html.

**Comment by WalterBright** [comment]
Under Compiler Changes:
```
Added compiler switch -profile=gc which instruments calls to memory allocation and writes
a report to the file profilegc.log upon program termination.
```

**Comment by 9rnsr** [comment]
The fine-grained commits are much better to review. LGTM.

**Pull request merged**
