### PR TITLE
use book style for all tables; also increase row spacing a little

### PR DESCRIPTION
**Pull request by aG0aep6G**
Properties before/after:
iconscreenshot1
std.range before/after:
iconscreenshot1

### CODE REVIEW

**Comment by andralex** [comment]
I think this is an improvement, but booktables look bad for very short and narrow tables, such as parameters. They look nice if the table is wide enough to occupy the entire page width. 

Therefore I'll pull this but I suggest @aG0aep6G you follow up with your previous work on tables and make it look sweet for small tables (2-4 entries, small width) and then apply that style appropriately. Thanks!

**Comment by CyberShadow** [comment]
I noticed something wrong here, not sure if it's related:

http://dlang.org/phobos-prerelease/std_algorithm_mutation.html

**Comment by aG0aep6G** [comment]
> I noticed something wrong here, not sure if it's related:
> 
> http://dlang.org/phobos-prerelease/std_algorithm_mutation.html

I don't think this PR has anything to do with it. The HTML is broken there:
```html
<div class="description"><table class="book"><caption>Cheat Sheet</caption></table><p></p>

<tr><th scope="col">Function Name</th> <th scope="col">Description</th></tr>
<p></p>
```

Looks like dmd inserts `<p></p>` on blank lines.

**Comment by CyberShadow** [comment]
I see, thanks. Probably another victim of DDOC_PARAGRAPH.

https://github.com/D-Programming-Language/dmd/pull/4342

**Pull request merged**
