### PR TITLE
align title "D Programming Language" with content text

### PR DESCRIPTION
**Pull request by aG0aep6G**
little-improvements

See commit messages for what changed exactly.

### CODE REVIEW

**Comment by CyberShadow** [comment]
I suggest splitting this PR into non-controversial changes and a separate pull request for the subjective ones. I'd merge a8786e5, 8d024fddc60f186d532fea4bf211ef97f4daee7b,  8573ad0 and  01f2e86 as-is.

**Comment by aG0aep6G** [comment]
The non-controversial parts: #814

**Comment by aG0aep6G** [comment]
Rebased so that this PR only has the controversial parts. Also added a commit to simply remove the GitHub ribbon. Unfortunately, rebasing changed commit hashes. I'll just copy the discussion so far:

##### On *menu: cast text shadows down, not up*:

CyberShadow commented on febe262 an hour ago
> I believe it's supposed to create the effect of inset (the light is above, but since the letters are inset the background, you see the dark parts of the inset "walls")

aG0aep6G commented on febe262 an hour ago
> If that's the intention, it doesn't work.

CyberShadow commented on febe262 32 minutes ago
> It looked fine to me until you told me they looked like shadows from a light source below :) Now I can't unsee it.

##### On *move search box to the right*:

CyberShadow commented on a143130 an hour ago
> This interferes with the "fork me" ribbon on download.html

aG0aep6G commented on a143130 40 minutes ago
> So that's why it's in that weird position. The fork ribbon also obscures the "Page Wiki" link. Move the ribbon, or an equivalent link, into #content?

CyberShadow commented on a143130 32 minutes ago
> Yeah, I'm not sure about imposing a constraint on all pages for the sake of a visual gimmick on one page. Although these ribbons were popular when they were announced, I haven't seen those on other websites in a while, it must have been a fad.

##### On *align title "D Programming Language" with content text*:

 CyberShadow commented on ca982d4 an hour ago 
> Might overlap with search boxes on narrow views.

 aG0aep6G commented on ca982d4 an hour ago 
> Not significantly more than already.

 CyberShadow commented on ca982d4 33 minutes ago 
> Let's do this only if we also move the search boxes.

**Comment by andralex** [comment]
rebase?

**Comment by CyberShadow** [comment]
Second commit was obsoleted by #816

**Comment by andralex** [comment]
should we close this then?

**Comment by CyberShadow** [comment]
First and third commits still apply, although I'm not a fan of the first.

**Comment by andralex** [comment]
@aG0aep6G ping

**Comment by aG0aep6G** [comment]
I'm on it.

**Comment by aG0aep6G** [comment]
rebased

**Comment by CyberShadow** [comment]
Still unmergeable.

**Comment by aG0aep6G** [comment]
rebased again

**Comment by aG0aep6G** [comment]
Could I get a decision on these?
Turn shadows around, yes/no?
Align "D programming language" with content text, yes/no?

**Comment by CyberShadow** [comment]
> Align "D programming language" with content text

I'll merge this.

**Comment by aG0aep6G** [comment]
Split off the text-shadows to another PR: #854. This only about the text alignment now.

**Comment by CyberShadow** [comment]
This appears to be incompatible with some recent changes, as now the header is incorrectly positioned.

**Comment by CyberShadow** [comment]
Sorry, my bad. Everything looks fine.

**Pull request merged**
