### PR TITLE
Reorder deprecated features.

### PR DESCRIPTION
**Pull request by ibuclaw**
Hitting two bird with one stone, as per discussion here: https://github.com/D-Programming-Language/dlang.org/pull/976#issuecomment-96258429

### CODE REVIEW

**Comment by andralex** [comment]
so prolly this needs surgery as well after we undo `if(arr)`

**Comment by ibuclaw** [comment]
Removed the ``if (arr)`` commit.

**Comment by ibuclaw** [comment]
By the way @andralex @WalterBright - would there be any merit in adding a ``-transition`` for use of 'delete' and 'scope' classes?  Similar as per here https://github.com/D-Programming-Language/dmd/pull/4611

**Comment by CyberShadow** [comment]
:+1: cc @MartinNowak

**Pull request merged**
