### PR TITLE
Issue 14900 - fix changelog example

### PR DESCRIPTION
**Pull request by MartinNowak**
[Issue 14900 – 2.068.0 change log example does not compile](https://issues.dlang.org/show_bug.cgi?id=14900)

### CODE REVIEW

**Comment by MartinNowak** [comment]
The feature doesn't completely work, so change the example to only show what works.

**Comment by 9rnsr** [comment]
it would be the best we can do just now.

**Comment by MartinNowak** [comment]
> it would be the best we can do just now.

Website is updated, it's still in the released docs and chm file, but I doubt that many people are reading that anyhow.

**Comment by 9rnsr** [comment]
Thank you again for your lightning work. > Website is updated,

> it's still in the released docs and chm file

If someone post bugzilla issue, I'll humbly receive the complaint.

**Pull request merged**
