### PR TITLE
Put bugtracker link under Community instead of Resources.

### PR DESCRIPTION
**Pull request by quickfur**
Per: http://forum.dlang.org/thread/kxvzuikgxmoxpduxdjel@forum.dlang.org

### CODE REVIEW

**Comment by quickfur** [comment]
Thanks!

**Comment by CyberShadow** [comment]
```
[2015-09-17 02:44:28] [Destructionator] why the hell is bugzilla linked to under community?
[2015-09-17 02:44:34] [Destructionator] it was the third place i looked to find it
```

**Comment by adamdruppe** [comment]
for the record, the first thing i checked was actually Compilers & Tools, since bug tracking is in my mind a tool relating to the compiler. Then I checked resources. Community was next only because the other options were even worse (it obviously isn't D reference or a Book)

**Comment by ZombineDev** [comment]
Wouldn't it be simpler for the users if the Bugzilla was a top-level menu item, right after DUB, and before community?

**Pull request merged**
