### PR TITLE
Update CodeMirror

### PR DESCRIPTION
**Pull request by CyberShadow**
http://forum.dlang.org/post/kterugwpstrrlybqlrdl@forum.dlang.org

https://issues.dlang.org/show_bug.cgi?id=15548

### CODE REVIEW

**Comment by aG0aep6G** [comment]
Bastiaan Veelo, who reported the issue to bugzilla, has confirmed the fix, and the files are just those from CodeMirror. So, LGTM.

**Comment by CyberShadow** [comment]
Of note is that to get `codemirror-compressed.js`, you have to follow a wizard, where you select which syntax, themes etc. you want to support. I don't know what settings were used originally, but the ones I used (D syntax and nothing else) seem to work fine in practice.

**Comment by aG0aep6G** [comment]
Has this been pushed online? Can the issue be marked fixed?

**Comment by CyberShadow** [comment]
It is now.

**Pull request merged**
