### PR TITLE
remove margin top from the home page heading

### PR DESCRIPTION
**Pull request by aG0aep6G**
It slipped through CSS, because it's not an &lt;h1&gt;.

Before/after:
iconscreenshot1

### CODE REVIEW

**Comment by CyberShadow** [comment]
What about the "Improve this page" buttons?

**Comment by aG0aep6G** [comment]
Yeah, they're clashing with the slogan now, forcing it to break:

iconscreenshot1

It's the same as on every other page now. But the home page is exceptionally long, of course, so that it happens easier.

I don't think it's too problematic. The slogan is overly long anyway. It has to be expected that it's broken in smaller windows.

**Comment by CyberShadow** [comment]
OK, then how about making the slogan only break if necessary, so it prefers a break after "The D programming language."?

```diff
diff --git a/index.dd b/index.dd
index fcb176d..42c51bd 100644
--- a/index.dd
+++ b/index.dd
@@ -2,8 +2,7 @@ Ddoc
 
 $(D_S D Programming Language,
 
-$(SECTION3 The D programming language. Modern
-convenience. Modeling power. Native efficiency.,
+$(SECTION3 The D programming language. $(SPAN style="display: inline-block", Modern convenience. Modeling power. Native efficiency.),
 
 Conference websites, videos and slides:
 $(UL
```

**Comment by aG0aep6G** [comment]
Sure thing. Updated.

**Pull request merged**
