### PR TITLE
add link to IDEs page

### PR DESCRIPTION
**Pull request by bitwise-github**
I believe that finding an IDE is an important part of getting started with D, and it should be listed on the Getting Started page.

### CODE REVIEW

**Comment by CyberShadow** [comment]
:+1:

**Comment by CyberShadow** [comment]
Though I hope this doesn't create the impression that D is tied to IDEs (technically, like VB, or ideologically, like Java).

**Comment by bitwise-github** [comment]
I suppose it could be changed to:
"Choose an IDE (optional).
$(LI $(LINK2 http://wiki.dlang.org/IDEs, $(B Choose)) an IDE (optional).)

**Comment by CyberShadow** [comment]
That or "Choose an IDE, or [set up your favorite editor](http://wiki.dlang.org/Editors)" OSLT. Though most editors have basic D support built-in.

**Comment by bitwise-github** [comment]
Ok, that sounds better. How about this?

$(LI Choose an $(LINK2 http://wiki.dlang.org/IDEs, $(B IDE)) or set up your favorite $(LINK2 http://wiki.dlang.org/Editors, $(B Editor)).
)

**Comment by joakim-noah** [comment]
Editor should not be capitalized but other than that, LGTM.  This link should have been there before, as others have noted.

**Comment by bitwise-github** [comment]
@joakim-noah It seems all the links are capitalized:

"The Books listed on the Wiki."
"Read the official Language"

I don't think "Books" or "Language" should be capitalized either, but I think I like the current style.

**Comment by joakim-noah** [comment]
Ah, yes, none should be capitalized, but it appears the original author chose to emphasize the links further by capitalizing them.  In that case, this pull follows the prevailing style and is fine.

**Comment by bitwise-github** [comment]
@joakim-noah indeed.

**Comment by bitwise-github** [comment]
So... is this waiting for approval from someone specific?

**Comment by bitwise-github** [comment]
ping?

**Comment by joakim-noah** [comment]
Maybe @CyberShadow forgot to merge?

**Pull request merged**
