### PR TITLE
fix grammar

### PR DESCRIPTION
**Pull request by aG0aep6G**
Just to spite Andrei :P
I totally expect this to be rejected.

Before/after:
iconscreenshot1

### CODE REVIEW

**Comment by CyberShadow** [comment]
I quite dislike this headline anyway. It sounds like something out of a car commercial.

Don't try to convince me to use your language - convince me that I want to use your language!

**Comment by quickfur** [comment]
LGTM.

If it were up to me, I'd rewrite that heading. But that risks Andrei vetoing the PR. :-P

**Comment by andralex** [comment]
Not sure the grammar argument is valid. That's a slogan, not a sentence. (To wit, neither version has a predicate.) The periods are intended to give it rhythm.

If you think this improves the slogan, make your case.

**Comment by WalterBright** [comment]
Thought I'd give it a go with a Shatnerian style:

The **D** .... Programming .... Language! modern ... **convenience** modern ... **power** native ... **efficiency**.
**Now** ... you're programming!

**Comment by aG0aep6G** [comment]
Consider these beauties:

	Beer. Water. Sand. Sunshine.
	Beer: water, barley, hops.

They're both working fine. Let's swap the punctuation around:

	Beer: water, sand, sunshine.

I think we agree that this is nonsense.

	Beer. Water. Barley. Hops.

This can make sense. Arrange beer, water, barley, and hops on a table; point at each and say its name: "Beer. Water. Barley. Hops.". But to see an is-made-of relation here, the reader has to ignore the punctuation which hints otherwise.

It's the same for the period-laden D slogan. The meaning can be guessed, but the punctuation hints otherwise. Judging by the periods, TDPL is on the same level as the other elements. But that's nonsense. To find meaning in the slogan, one has to ignore the stated relation of TDPL to the others, and substitute one that makes sense.

Regarding ryhthm, if read without interpreting, the period version is four monotone fragments, whereas the colon-comma version has something going on. (Caution, starts audio right away!) [Listen to a computer reading it.](http://CodeWelt.com/proj/speak?lang=en-us&text=A.%20B.%20C.%20D.%0DA:%20B,%20C,%20D.%0D%0DBeer.%20Water.%20Barley.%20Hops.%0DBeer:%20water,%20barley,%20hops.%0D%0DThe%20D%20programming%20language.%20Modern%20convenience.%20Modelingpower.%20Native%20efficiency.%0DThe%20D%20programming%20language:%20modern%20convenience,%20modelingpower,%20native%20efficiency.) (Wrote 'modelingpower' here, because standalone 'modeling' would be mistaken for an attribute. This is another issue with the slogan.)

I'm wasting way too much time on this :)

**Comment by andralex** [comment]
Ionno. Consider literally the first hit when searching slogans: http://www.hongkiat.com/blog/77-catchy-and-creative-slogans/

* MacPro: Beauty outside. Beast inside.
* Harley Davidson: American by birth. Rebel by choice.
* Survivor: Outwit. Outplay. Outlast.
* TagHeuer: Success. It's a mind game.
* Olympus: Your vision. Our future.
* eBay: Buy it. Sell it. Love it.

That's, what, 6 out of 77. There are a few using commas-based patterns as well, but overall I don't see how there's a case for replacing one with the other. Will close now, feel free to follow up or reopen if there's more evidence.

**Comment by aG0aep6G** [comment]
Notice how you put colons there, to distinguish the brand from the slogan. And the fragments in the slogans are all on the same level.

It's not "MacPro. Beauty outside. Beauty inside.".

If the D slogan was "Modern convenience. Modeling Power. Native Efficiency." you'd have a point. Putting "The D Programming Language." in front breaks it, though.

Also, let's see how the slogans are actually used, if they're still in use:
* <https://www.apple.com/mac-pro/> says "Built for creativity on an epic scale." now.
* Can't find the slogan on <http://www.harley-davidson.com/content/h-d/en_US/home.html>.
* On <http://www.cbs.com/shows/survivor/>, the add for the T-Shirt says: "Outwit, Outlast, Outplay", with commas. On the logo there is no punctuation.
* <http://us.tagheuer.com/en/home> says "SWISS AVANT-GARDE SINCE 1860" and "DON'T CRACK UNDER PRESSURE".
* <http://www.olympus-global.com/en/> has a **comma** in the logo.
* No slogan to be found on <http://www.ebay.com/>.

**Pull request closed without merging**
