### PR TITLE
Fix documented order of evaluation

### PR DESCRIPTION
**Pull request by tgehr**
In accordance with http://forum.dlang.org/thread/pgrfvbffrviwjudeawvz@forum.dlang.org#post-mjtihl:2424a3:241:40digitalmars.com.

### CODE REVIEW

**Comment by andralex** [comment]
Thanks! We should make this pull contingent upon the appropriate compiler changes.

**Comment by tgehr** [comment]
It still includes the warning that DMD does not comply yet, so why not pull it now?

**Comment by JinShil** [comment]
I would like to see this merged with or without changes to the compiler.  It is also my opinion that more pull requests like this should be encouraged, as proper definition should precede implementation.  With the specification nailed down, users don't have to wonder "Is this a bug, or by design?".  Having a clear specification will enable users to file bug reports with confidence and actually aid the implemention by providing test cases that compiler devs can use to verify their work (i.e. teamwork in disguise).  I have passed, a few times, on filing bug reports simply because I could't reconcile what the language designers intended.

**Comment by Hackerpilot** [comment]
I agree. The note that DMD does not currently follow the standard has not been removed, so I don't see any harm in pulling this.

**Comment by ibuclaw** [comment]
:+1:

**Pull request merged**
