### PR TITLE
Integrate forum activity summary into dlang.org front page

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Maybe a little more towards the bottom?

**Comment by CyberShadow** [comment]
Below the example? It would be below the fold then, I think @andralex wants it to be front and center.

**Comment by MartinNowak** [comment]
My first thought was, quite a lot of information. But then again, it's quite a good idea to make the forum more present.

**Comment by CyberShadow** [comment]
@andralex Awaiting your feedback.

**Comment by andralex** [comment]
My first impression: looks nice but I think everything should be smaller and "thinner". Essentially a la Facebook, which crams a bunch of good stuff in small spaces by using small but highly readable fonts, pictograms, and images. How about trying a few other (and smaller) fonts?

**Comment by quickfur** [comment]
Agree that the fonts for the forum topics are a smidgen too large. Also, I think the code example should come first, since a newcomer would be more interested primarily in the language itself (that the code sample shows off) than the discussions surrounding the language. First you want to draw the reader to the language itself, then when some interest has registered, present the forum as a place to find out more of the latest-and-greatest on the language.

**Comment by CyberShadow** [comment]
Now?

**Comment by p0nce** [comment]
I think the forum activity should be in a separate panel much like the twitter feed. As of now it breaks the language presentation in parts.

**Comment by CyberShadow** [comment]
Should I just stack the two columns on top of each other and put them above the Twitter feed?

> pictograms, and images

I could add a small avatar of the thread author.

**Comment by michaelc37** [comment]
yea, it seems a bit awkward to this information in the center while the twitter feed is on the right. 

i think they might look better as separate columns above/below the twitter feed.

**Comment by JinShil** [comment]
> Should I just stack the two columns on top of each other and put them above the Twitter feed?

I like this idea, if you make each feed collapsable like the sidenav.

**Comment by CyberShadow** [comment]
Why would you ever want to collapse them, though? They'll only appear on the front page.

How about I will make them scrollable instead (like right now), and we can play with the number of visible rows if it ends up too tall.

**Comment by JinShil** [comment]
> Why would you ever want to collapse them, though? They'll only appear on the front page.

So I don't have to scroll down, read the posts, then scroll back up to select something else towards the top.  

But do as you wish.

**Comment by CyberShadow** [comment]
Surely scrolling is much easier than clicking a relatively tiny target???

I can understand that with navigation, having everything expanded is unwieldy, makes finding what you want harder, and can increase the page length for short pages.

**Comment by JinShil** [comment]
> Surely scrolling is much easier than clicking a relatively tiny target???

If your prefer scrolling, you don't have to click to collapse.

**Comment by CyberShadow** [comment]
!()[http://dump.thecybershadow.net/2df91276e145cd544b4b2fead2283421/00000142.png]

**Comment by JinShil** [comment]
Looks good!

**Comment by quickfur** [comment]
:+1:

**Comment by andralex** [comment]
love it!!!

**Comment by andralex** [comment]
@CyberShadow wait, I just pushed and it doesn't look like your latest screenshot. Was that just a mockup?

**Comment by CyberShadow** [comment]
Sorry, yeah, since I have to keep things in sync with the forum I have local URLs changed to localhost, which is why the pull was out of date. And I need to update the "production" forum instance.

**Comment by CyberShadow** [comment]
Real pull: https://github.com/D-Programming-Language/dlang.org/pull/823

**Comment by jacob-carlborg** [comment]
@andralex @CyberShadow there's a big 404 on the main page because `http://forum.dlang.org/frame` doesn't exist.

**Pull request merged**
