### PR TITLE
We should be including core.stdc in the menu

### PR DESCRIPTION
**Pull request by schveiguy**

### CODE REVIEW

**Comment by schveiguy** [comment]
Note, the vast number of additions is just because the menu appears in every single html file, and we are adding many links to the menu. The files themselves were already generated and on the server.

**Comment by JackStouffer** [comment]
I don't see why not.

LGTM

**Comment by CyberShadow** [comment]
LGTM though can't vouch for the Windows patch.

**Comment by schveiguy** [comment]
Windows uses c too, no?

**Comment by CyberShadow** [comment]
Yeah. What I meant is that I can't test the win32.mak patch right now.

**Comment by schuetzm** [comment]
The win32.mak change is trivial, let's just risk it.

**Comment by schveiguy** [comment]
thanks!

**Pull request merged**
