### PR TITLE
Word wrap long menu names

### PR DESCRIPTION
**Pull request by JinShil**
word_wrap

### CODE REVIEW

**Comment by MartinNowak** [comment]
Yikes, how about a variable sized menu instead?

**Comment by CyberShadow** [comment]
Can we insert a zero-width space after each `.` so it doesn't break in the middle of each word?

**Comment by JinShil** [comment]
> Can we insert a zero-width space after each . so it doesn't break in the middle of each word?

That's a good idea.  Please give me 24 hours to modify.

**Comment by MartinNowak** [comment]
> Can we insert a zero-width space after each . so it doesn't break in the middle of each word?

How about omitting the `std` prefix?
Also `std.container` should be another submenu IMO, but that's a bit more work.

**Comment by CyberShadow** [comment]
> Also std.container should be another submenu IMO, but that's a bit more work.

We should avoid nesting things too deeply, as that's more clicks and complexity.

**Comment by JinShil** [comment]
Added zerowidth breaking space.

wrap2

I will submit another pull request to experiment with some of @MartinNowak 's ideas.

**Comment by JinShil** [comment]
> How about omitting the std prefix?

Sorry @MartinNowak, I tried to do that, but it turned out to be a little more difficult than I anticipated due to the way the DDoc macros were written... and I'm not that invested.

**Comment by andralex** [comment]
I'll pull this because it's useful regardless of later improvements.

**Pull request merged**
