### PR TITLE
Fix crash in index sample code

### PR DESCRIPTION
**Pull request by landaire**
The example on dlang.org's index page which rounds floats currently crashes when ran. If you dump out `args` you can see that for some reason it's getting an empty string as `arg[1]`: `["./f347", ""]`

To "fix" this, I just removed support for reading from args.

```
std.conv.ConvException@/opt/compilers/dmd2/include/std/conv.d(2402): Floating point conversion error for input "".
----------------
??:? pure @safe bool std.exception.enforce!(bool).enforce(bool, lazy object.Throwable) [0x4b57ee]
??:? pure @safe real std.conv.parse!(real, immutable(char)[]).parse(ref immutable(char)[]) [0x4c8eee]
??:? pure @safe real std.conv.toImpl!(real, immutable(char)[]).toImpl(immutable(char)[]) [0x4ca1b9]
??:? pure @safe real std.conv.to!(real).to!(immutable(char)[]).to(immutable(char)[]) [0x4c8ea3]
??:? @safe real std.functional.__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ.compose!(immutable(char)[]).compose(immutable(char)[]) [0x4c8e6b]
??:? @safe immutable(char)[] std.functional.__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ.compose!(immutable(char)[]).compose(immutable(char)[]) [0x4c8e33]
??:? @property @safe immutable(char)[] std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult.front() [0x4cb006]
??:? ref @safe std.algorithm.iteration.joiner!(std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult, immutable(char)[]).joiner(std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult, immutable(char)[]).Result std.algorithm.iteration.joiner!(std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult, immutable(char)[]).joiner(std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult, immutable(char)[]).Result.__ctor(std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult, immutable(char)[]) [0x4cb477]
??:? @safe std.algorithm.iteration.joiner!(std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult, immutable(char)[]).joiner(std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult, immutable(char)[]).Result std.algorithm.iteration.joiner!(std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult, immutable(char)[]).joiner(std.algorithm.iteration.__T9MapResultS1633std10functional136__T7composeS253std4conv11__T2toTAyaZ2toS933std10functional67__T7composeS27_D3std4math5roundFNbNiNeeZeS223std4conv9__T2toTeZ2toZ7composeZ7composeTAAyaZ.MapResult, immutable(char)[]) [0x4cb2c9]
??:? _Dmain [0x4a7746]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x4dbe82]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x4dbdd8]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x4dbe3e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x4dbdd8]
??:? _d_run_main [0x4dbd35]
??:? main [0x4d7669]
??:? __libc_start_main [0x40b6ba14]
```

### CODE REVIEW

**Comment by JackStouffer** [comment]
The change looks fine, but I think the real solution is figuring out why it's getting the garbage values in the first place.

Anyone else know why this would be the case?

**Comment by landaire** [comment]
Looks like it's actually a bug in http://dpaste.dzfl.pl/. The same sample on that site: http://dpaste.dzfl.pl/cd468977b7cd

**Comment by CyberShadow** [comment]
https://issues.dlang.org/show_bug.cgi?id=15050

**Comment by JackStouffer** [comment]
@CyberShadow Well, we can't wait for that new backend forever. I'd vote to merge this for the time being, as it's better to have a less complete example that runs.

**Comment by landaire** [comment]
I agree. I mentioned to a friend that D can interop with Objective-C code and he went to the site to check it out, ran the sample, got a stack trace. Not the best first impression.

**Comment by andralex** [comment]
Thanks @CyberShadow for submitting the bug. Change is good independently of the bug. Thx!

**Pull request merged**
