### PR TITLE
Nicer front page notices

### PR DESCRIPTION
**Pull request by CyberShadow**
The notices on the front page look a bit ad-hoc at the moment.

### CODE REVIEW

**Comment by CyberShadow** [comment]
It doesn't really fit into the rest of the page's style, but this is the best I could think of for the moment. If anyone has better design ideas they are welcome to share them.

**Comment by MartinNowak** [comment]
fancy

**Comment by MartinNowak** [comment]
Square corners, little less drop shadow and nicer colors would make it even better.

**Comment by MartinNowak** [comment]
see #949

**Pull request merged**
