### PR TITLE
This comment is stale...

### PR DESCRIPTION
**Pull request by smandy**

### CODE REVIEW

**Comment by CyberShadow** [comment]
It should probably be replaced with other DConf news?

@andralex

**Comment by MartinNowak** [comment]
We should keep a link to dconf, maybe something like #512.

**Comment by smandy** [comment]
either way - having an 'open till XXX' when 'XXX' is already in the past is bad. Needs to be cleaned up one way or the other

**Comment by smandy** [comment]
addressed this (hopefully) in PR #931

**Comment by MartinNowak** [comment]
Thx

**Pull request closed without merging**
