### PR TITLE
HTML5 validation fixes

### PR DESCRIPTION
**Pull request by CyberShadow**
Depends on #805. Needs rebasing before merging.

This fixes a number of validation errors, as identified on dlang.org by the W3C validator.

In general this is many small changes. See each commit for details.

### CODE REVIEW

**Comment by andralex** [comment]
alrighty rebase time

**Comment by CyberShadow** [comment]
Rebased.

**Comment by andralex** [comment]
sweet thanks

**Comment by MartinNowak** [comment]
Thanks

**Pull request merged**
