### PR TITLE
Upgrade dpl-docs dependencies.

### PR DESCRIPTION
**Pull request by s-ludwig**
Updates to the latest versions of vibe.d (compiles with the latest DMD 2.069.0 beta) and Ddox (containing various fixes).

### CODE REVIEW

**Comment by s-ludwig** [comment]
Updated version of #1108

**Comment by CyberShadow** [comment]
http://dtest.thecybershadow.net/artifact/website-ea1e4f584ad3f17fe22f060eba662d1288fbd4e2-d022e2015ddd9b0fba1b7afacc3c5cf5/web/library-prerelease/core/atomic/atomic_load.html

For some reason the example has a leading and trailing line full of tabs.

**Comment by s-ludwig** [comment]
This is a regression caused by https://github.com/rejectedsoftware/ddox/pull/102. I'll update the PR once this is fixed and tagged.

**Comment by s-ludwig** [comment]
Updated. Also fixes the title for enum members:
http://dlang.org/library/std/compiler/vendor.dot_net.html
vs.
http://dtest.thecybershadow.net/artifact/website-51c8017fcb657a67c14707fb19c0cd5adc2f5197-29831c8f01c17322730452608e2a7f29/web/library/std/compiler/vendor.dot_net.html

**Comment by s-ludwig** [comment]
Looks like there is a regression for `std.algorithm.searching` somewhere: http://dtest.thecybershadow.net/artifact/website-51c8017fcb657a67c14707fb19c0cd5adc2f5197-29831c8f01c17322730452608e2a7f29/web/library/std/algorithm/searching.html

**Comment by s-ludwig** [comment]
For some reason the latest build didn't find version 0.11.3 of DDOX, although it exists on the registry: http://code.dlang.org/packages/ddox
Instead it fell back to 0.11.2 which still has the broken macro processing.

**Comment by CyberShadow** [comment]
You can force-push a non-change (update commit time) to force a retest.

**Comment by s-ludwig** [comment]
Unfortunately didn't help. Probably this is caused by https://github.com/D-Programming-Language/dub/issues/528

**Comment by s-ludwig** [comment]
OK, looking good now.

**Comment by CyberShadow** [comment]
http://dtest.thecybershadow.net/artifact/website-2938f650a10e7b95919e69bf29626d80a7db8909-47caf91807c3b1e6241158411fe304e2/web/library/core/time/duration.op_binary.html

`Duration` appears twice in the title (`Duration.Duration`).

Is the new style for prototype code blocks intentional?

**Comment by s-ludwig** [comment]
> Is the new style for prototype code blocks intentional?

Hm, no, the style sheet is missing an update.

**Comment by CyberShadow** [comment]
> Hm, no, the style sheet is missing an update.

So what's the action item here? We *could* just merge this, it's not *too* ugly...

**Comment by s-ludwig** [comment]
I just wanted to fix the headings first. The style was fixed already, I just forgot to push.

**Comment by s-ludwig** [comment]
Headings for multiple nested declarations look right now.

**Comment by CyberShadow** [comment]
Looks great, thanks!

**Pull request merged**
