### PR TITLE
integrate news column in menu

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Just an idea, this works nicer for narrow screens.
You can see a preview here https://dlang.dawg.eu/.
newsinmenu

**Comment by MartinNowak** [comment]
BTW, would be nice if the forum iframes were available over https.

**Comment by CyberShadow** [comment]
> BTW, would be nice if the forum iframes were available over https.

Both dlang.org and forum.dlang.org use self-signed certificates. The iframes will probably work via https if you first go to forum.dlang.org and accept the self-signed certificate.

**Comment by CyberShadow** [comment]
Let's please not make the navigation *even wider* for all pages.

**Comment by CyberShadow** [comment]
Is this necessary, considering the average viewport size? Over 93% of people use a resolution over 1280px wide according to [this](http://www.w3schools.com/browsers/browsers_display.asp).

**Comment by MartinNowak** [comment]
Lots of programmers use their monitor in vertical mode. We could do this with a media query, depending on the available width.

**Comment by CyberShadow** [comment]
OK. The other side of the coin is that this puts the news "below the fold", and I'm not sure if additional media queries are worth it from the complexity perspective. But we can get a third opinion.

**Comment by MartinNowak** [comment]
Let's ask @aG0aep6G who did #886.

**Comment by MartinNowak** [comment]
It looks a bit weird, clutters the menu and makes it fatter and generally looks a bit unbalanced.
So I'll close this, still would like to see a good idea how to not squeeze the main content.
In general it seems like we should clean up the index, the example is horrible and the important main points are drown in details.
A brief paragraph and fanouts to http://dlang.org/convenience, http://dlang.org/power, and http://dlang.org/efficiency might work much better.

**Pull request closed without merging**
