### PR TITLE
Split off CONTRIBUTING.md from README.md.

### PR DESCRIPTION
**Pull request by quickfur**
Details about contributing should go into CONTRIBUTING.md; README.md should just explain what this repo is about.

### CODE REVIEW

**Comment by CyberShadow** [comment]
There should probably be a link from README to CONTRIBUTING.

You can do cross-links on GitHub Markdown: http://stackoverflow.com/a/7658676/21501

**Comment by quickfur** [comment]
Done

**Comment by CyberShadow** [comment]
:+1:

**Comment by quickfur** [comment]
Thanks!

**Pull request merged**
