### PR TITLE
New logo proposal

### PR DESCRIPTION
**Pull request by p0nce**
I thought I would give it a try and make something more into the current hype.
Included SVG derived from the original logo.

### CODE REVIEW

**Comment by p0nce** [comment]
Before:
Before

After:
After

**Comment by AndrejMitrovic** [comment]
A little too sharp on the edges for my taste. Could you make it a bit rounded and see what that looks like? :)

**Comment by CyberShadow** [comment]
#812 moved the title to the right. Another tweak you could try is to make the logo as wide as the navigation.

**Comment by p0nce** [comment]
@AndrejMitrovic Erm, let me see another day. Spent hours already. I don't really like rounded edges everywhere like on the current site, but it makes sense to have subtle ones like on the menu. Can't guarantee it will look better.

@CyberShadow Makes sense. Maybe we can display the SVG directly then (the PNG is exactly the SVG render). But going to be now.

**Comment by WalterBright** [comment]
I appreciate the work you've put in, but I'd like to keep the current logo:

1. logo consistency is very important for branding. We've done a good job associating D with the current logo
2. I like the enameled look of the current one
3. I like the current rounded edges, the subtle variation in color, the soft edges of the D part, the D fills the logo, etc.

**Comment by CyberShadow** [comment]
> logo consistency is very important for branding

A lot of companies (possibly all major ones) tweak their logo over time while keeping the core theme.

See for yourself: https://www.google.com/search?tbm=isch&q=logo+evolution

**Comment by WalterBright** [comment]
I know some do. But not that quickly, and they launch new logos with marketing campaigns.

**Comment by CyberShadow** [comment]
BTW, please use PNG for screenshots.

**Comment by andralex** [comment]
BDFL-induced closing.

**Comment by CyberShadow** [comment]
The comments of this week's This Week in D seem to centralize on the need of a new logo:

https://www.reddit.com/r/programming/comments/2tozgb/this_week_in_d_website_makeover_c_interop_import/

@WalterBright I suggest that you reconsider.

**Comment by WalterBright** [comment]
There's no rationale given, either here or on reddit or on the other PR for a logo change. Changing an established logo is not something to be taken lightly. Let's not spend resources on an illusion of progress.

**Comment by CyberShadow** [comment]
What's the rationale of all the work we've been doing this week on changing the website design?

**Comment by p0nce** [comment]
Wow I didn't want to launch such a heated debate, it was really just a proposal.

I'm fully OK with the logo staying as it is: branding is indeed important and I like BDFL decisions.

I just wanted to try another thing and eventually make more material for D-related stuff like "d-idioms" or "This Week In D" where the current logo looks odd.

I will use this logo for "d-idioms" not because I think it looks better (such a statement I can't make, for example the original logo has lovely reflections) but because my logo will integrate better in the surroundings on this site.

**Comment by WalterBright** [comment]
I do appreciate the effort you put into helping out! Thank you

**Comment by AndrejMitrovic** [comment]
We should make a couple of proposal and the post to reddit and ask on opinions whether the logo should change. Then it's practically automatically accepted as the new logo (just like the recent *@changes*).

**Comment by aldanor** [comment]
While I don't personally like the redesign suggested above (or maybe it just lacks a few finishing touches and detail here and there), I think it may be a move in the right direction since the current logo is a bit tacky/90's-style and may seem completely oddball when slapped on an otherwise polished website with a design that tries to stay modern. Redesigning it is then a matter of making it more compatible with other content -- that should be the primary reason and not just doing it for the sake of it.

> logo consistency is very important for branding

I agree; but while this is true in general, the subtle design details may have to be changed in order to keep in touch with the latest trends. E.g., Microsoft, Google and Apple:
- http://gizmodo.com/the-evolution-of-googles-iconic-logo-1582297667
- http://blogs.windows.com/bloggingwindows/2012/02/17/redesigning-the-windows-logo/
- http://blogs.tribune.com.pk/story/19792/the-evolution-of-the-apple-logo/

**Comment by p0nce** [comment]
> the current logo is a bit tacky/90's-style and may seem completely oddball when slapped on an otherwise polished website with a design that tries to stay modern. Redesigning it is then a matter of making it more compatible with other content -- that should be the primary reason and not just doing it for the sake of it.

Exactly my point, that's why new logo proposal keep the "D + planet" shape.

**Pull request closed without merging**
