### PR TITLE
Switch default font to Roboto and code font to Roboto Mono

### PR DESCRIPTION
**Pull request by andralex**
Preview: http://erdani.com/d/phobos-prerelease/

### CODE REVIEW

**Comment by CyberShadow** [comment]
Here's how it looks for me:



The difference in font size and weight for the main and code fonts is rather jarring. Do you see this too?

**Comment by CyberShadow** [comment]
For comparison, the current version:

**Comment by andralex** [comment]
Looks quite a bit better on my machine: 

screen shot 2015-06-05 at 4 22 47 pm

**Comment by andralex** [comment]
the bold font in inline code makes it misaligned, so I'll replace with regular

**Comment by andralex** [comment]
updated inline code, still looking misaligned

**Comment by JinShil** [comment]
Code looks especially weird.  Check out the upper arches of the fonts in this image.
fonts

**Comment by CyberShadow** [comment]
I think lack of hinting is showing. And the font in the navigation menu is silly-small now.

**Comment by CyberShadow** [comment]
Umm, how come this pull request isn't merged but I'm seeing the new fonts on dlang.org?

**Comment by CyberShadow** [comment]
Reuploaded the website from the staging area due to:

http://beta.forum.dlang.org/post/fxmzsabcxugkctlaphld@forum.dlang.org

**Comment by CyberShadow** [comment]
OK to close considering the issues we ran into?

**Comment by JinShil** [comment]
Please close this.

**Pull request closed without merging**
