### PR TITLE
remove documentation for -property

### PR DESCRIPTION
**Pull request by aG0aep6G**
Related dmd PRs:
https://github.com/D-Programming-Language/dmd/pull/4955
https://github.com/D-Programming-Language/dmd/pull/4862 (follow-up to the above)

### CODE REVIEW

**Comment by aG0aep6G** [comment]
This should maybe not be pulled before the 2.069 release.

**Comment by aG0aep6G** [comment]
Uhh, no waiting until 2.069 then? 2.068 still has a working `-property`.

**Comment by DmitryOlshansky** [comment]
> Uhh, no waiting until 2.069 then? 2.068 still has a working -property.

Well 2.068 is out, all we merge afterwards is bound for 2.069

**Comment by aG0aep6G** [comment]
The release cycle isn't followed with the website, or is it now? I'm sure I've seen website updates without a release.

**Comment by MartinNowak** [comment]
> The release cycle isn't followed with the website, or is it now? I'm sure I've seen website updates without a release.

We do update the website in between releases, that won't here though.

**Comment by aG0aep6G** [comment]
With the 2.068.1 release this has now been pushed online. That means http://dlang.org/dmd-windows.html and friends don't document `-property` anymore, but the current compiler still has the switch.

**Pull request merged**
