### PR TITLE
add link to beta downloads (commented out)

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by CyberShadow** [comment]
We have enough horizontal space to simply duplicate the download buttons for all platforms in a second column.

**Comment by andralex** [comment]
So what would be the process of uncommenting?

**Comment by CyberShadow** [comment]
Unwrap the contents of the `$(COMMENT ...)` block.

**Comment by MartinNowak** [comment]
> We have enough horizontal space to simply duplicate the download buttons for all platforms in a second column.

Right, will work on that.

**Pull request merged**
