### PR TITLE
function.html: add simple navigation

### PR DESCRIPTION
**Pull request by WalterBright**
Sorely needed.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Doesn't look all that great... how about a list?

**Comment by WalterBright** [comment]
I like having it be horizontal because there are a lot of items and a long vertical list is rather unpleasant.

In any case, nobody ever likes my styling. But these pages desperately need navigation, nobody ever adds it, so I suggest pulling it and someone who is ~~more popular~~ better at styling can then style it.

**Comment by CyberShadow** [comment]
Heh, OK.

**Comment by WalterBright** [comment]
thanks

**Comment by CyberShadow** [comment]
Actually, is the navigation at the top even needed? With the `LNAME2` changes by themselves, you can get a link to the section by clicking the section title.

**Comment by CyberShadow** [comment]
https://github.com/D-Programming-Language/dlang.org/pull/1145

**Comment by WalterBright** [comment]
> Actually, is the navigation at the top even needed? With the  LNAME2  changes by themselves, you can get a link to the section by clicking the section title.

I don't know what that means. There was no existing navigation.

**Comment by CyberShadow** [comment]
> I don't know what that means. There was no existing navigation.

This PR changes two things:

1) Each heading is now an anchor, and thanks to some JS is also clickable. You can get the link to a section simply by clicking the heading.

2) It adds the "navigation" blob at the top.

What I meant is that 2) isn't that necessary because of 1).

**Pull request merged**
