### PR TITLE
html doc build for dmd

### PR DESCRIPTION
**Pull request by andralex**
Works in conjunction with https://github.com/D-Programming-Language/dmd/pull/5352.

### CODE REVIEW

**Comment by andralex** [comment]
@CyberShadow do you know why this might have happened? http://dtest.thecybershadow.net/results/57c4402ecd7285277ea0da611679fc83f4e490e0/dd10bb6137ed229bcb872c6611942ae183a0a031/build.log

**Comment by CyberShadow** [comment]
I'm guessing you didn't specify whichever dependency generates `.generated/2.069.2.ddoc` for the dmd documentation target.

**Comment by andralex** [comment]
Ah, it depends on the entire `$(STD_DDOC_PRE)`. Fixed.

**Comment by andralex** [comment]
@CyberShadow thx!!

**Comment by andralex** [comment]
"All checks have passed"

**Comment by CyberShadow** [comment]
Looks like the tools section is generating broken HTML

**Comment by adamdruppe** [comment]
@andralex @CyberShadow so what's the status here?

**Comment by CyberShadow** [comment]
The tools section is still generating broken HTML. Look at the top of any generated file.

**Comment by CyberShadow** [comment]
Seeing as Andrei seems to be busy with more important things, does anyone want to adopt this PR?

**Comment by andralex** [comment]
OK, fixed. This + https://github.com/D-Programming-Language/dmd/pull/5617 = win

**Comment by JackStouffer** [comment]
Looking good :+1:

This is missing one thing however, there needs to be a link somewhere on the site, perferably in the navbar, to these docs.

**Comment by WalterBright** [comment]
Here it is in all its glory: http://dlang.org/dmd-prerelease/

**Comment by JackStouffer** [comment]
Better than nothing I guess

**Pull request merged**
