### PR TITLE
remove upcoming changelog

### PR DESCRIPTION
**Pull request by MartinNowak**
- upcoming changes are now handled in separate
  changelog files per repo

### CODE REVIEW

**Comment by MartinNowak** [comment]
See https://github.com/D-Programming-Language/phobos/pull/3699.

**Comment by aG0aep6G** [comment]
Remove it from win32.mak, too. Maybe save the REMEMBER stuff somewhere.

**Comment by MartinNowak** [comment]
> Maybe save the REMEMBER stuff somewhere.

It's already in the wiki.

**Comment by aG0aep6G** [comment]
LGTM

**Pull request merged**
