### PR TITLE
Add 301 redirect for pages moved to the wiki.

### PR DESCRIPTION
**Pull request by JinShil**
I'll delete the temporary page if this gets accepted.  I have a couple more I'd like to do, but this is an initial test that I'm doing things right.

### CODE REVIEW

**Comment by CyberShadow** [comment]
That doesn't look like the correct RewriteRule syntax. The response code doesn't go in front.

> I'll delete the temporary page if this gets accepted.

The website should work offline without a web server, so the redirect page should probably stay.

**Comment by CyberShadow** [comment]
BTW, I didn't say that a HTTP redirect wouldn't be an improvement.

Also, we can probably remove the .html page if there are no links to it in our current documentation.

**Comment by JinShil** [comment]
> That doesn't look like the correct RewriteRule syntax. The response code doesn't go in front.

I didn't intend to use mod_rewrite, but I forgot to change `RewriteRule` to `Redirect`.  No rewrite is needed for these, so a simple redirect seems more straightforward.  

> The website should work offline without a web server, so the redirect page should probably stay.

If this PR is merged I'll submit a separate pull request to delete those pages, and the decision can be made there.

**Comment by andralex** [comment]
Alrighty let's see...

**Pull request merged**
