### PR TITLE
fancy tables

### PR DESCRIPTION
**Pull request by aG0aep6G**
Mostly copied from Sebastiaan Koppe.

iconscreenshot1

### CODE REVIEW

**Comment by CyberShadow** [comment]
Can you reuse an existing color or its hue? I don't think we use that shade of gray anywhere now.

**Comment by aG0aep6G** [comment]
Changed colors. Updated screenshot above.

**Comment by andralex** [comment]
Nice. I want to keep booktable because it looks nice for wide entries. Also vertical lines are unrecommended in classical typography, see e.g. http://www.inf.ethz.ch/personal/markusp/teaching/guides/guide-tables.pdf.

So: @aG0aep6G could you please keep the booktable class BUT keep your proposed style for default tables? We'll use the default style for short tables.

Also please eliminate all dotted lines. Vertical ones are not nice anyway, and the horizontal ones are rendered unnecessary by the stripes in the background. Thanks!

**Comment by aG0aep6G** [comment]
I'd rather not go with two different styles. If you like the 'book' style, I suggest making that the one table style:  #842

**Comment by andralex** [comment]
@aG0aep6G Well we already have a different kind of table for "Parameters". That looks nice enough, but if you feel like improving it please revive this. Thanks!

**Pull request closed without merging**
