### PR TITLE
Update the grammar to allow Args[0].T to be a type.

### PR DESCRIPTION
**Pull request by legrosbuffle**
See the corresponding pull request here:
https://github.com/D-Programming-Language/dmd/pull/4516

### CODE REVIEW

**Comment by legrosbuffle** [comment]
@9rnsr

**Comment by 9rnsr** [comment]
Thanks!

**Comment by 9rnsr** [comment]
Ah, could you also fix the grammar in `declaration.dd`? For readability that's currently duplicated...

**Comment by legrosbuffle** [comment]
Sure, done.

**Pull request merged**
