### PR TITLE
Document AA .byKeyValue().

### PR DESCRIPTION
**Pull request by quickfur**
Needed by: https://github.com/D-Programming-Language/druntime/pull/1070

### CODE REVIEW

**Comment by MartinNowak** [comment]
There is no delegate involved, can you please fix that?

**Comment by MartinNowak** [comment]
How about a two-liner for the [changelog](https://github.com/D-Programming-Language/dlang.org/blob/master/changelog.dd)?

**Comment by quickfur** [comment]
Fixed, I had just copied the wording from `byKey` and `byValue` but obviously they are out of date.

**Comment by quickfur** [comment]
@MartinNowak What exactly needs to be done in changelog.d? I'm unsure where things should go, esp. since the dates there are no later than 2012.

**Comment by schveiguy** [comment]
LGTM

**Comment by AndrejMitrovic** [comment]
@quickfur: You're looking at `changelog.d` instead of `changelog.dd`.

I don't know why we keep these confusing names, I would at least rename the old one to `old-changelog.d` or something. Several people tripped on this before.

**Comment by AndrejMitrovic** [comment]
Thanks!

**Comment by MartinNowak** [comment]
https://github.com/D-Programming-Language/dlang.org/pull/744

**Comment by quickfur** [comment]
Changelog update: https://github.com/D-Programming-Language/dlang.org/pull/745

**Pull request merged**
