### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**
Conflicts:
	changelog.dd

### CODE REVIEW

**Comment by MartinNowak** [comment]
So that we can publish the changelog for the beta.

**Comment by MartinNowak** [comment]
Let's remove the array bool thing first #1046.

**Comment by 9rnsr** [comment]
> Let's remove the array bool thing first #1046.

OK, it's merged. I think this PR should be updated to merge from latest stable branch.

**Comment by MartinNowak** [comment]
Updated

**Comment by 9rnsr** [comment]
Thanks.

**Pull request merged**
