### PR TITLE
bugstats.php - HTML fixes

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by aG0aep6G** [comment]
Changes look good to me.

There's still something going wrong with the `DISPLAY` macro. It generates nonsense like this:
`<font color=Blocker, y_axis_field=bug_severity&amp;query_format=report-table&amp;product=D&amp;bug_status=NEW&amp;bug_status=ASSIGNED&amp;bug_status=REOPENED&amp;bug_severity=blocker>`

**Comment by CyberShadow** [comment]
> There's still something going wrong with the DISPLAY macro

Andrei removed the third parameter from invocations in 51c978a631167669302afefff3f70e7a1fa0ee65, but did not remove it from the macro. It look like out-of-bounds parameter indexes act like `$0` (meaning, paste all parameters).

**Comment by CyberShadow** [comment]
Anything else?

**Comment by aG0aep6G** [comment]
LGTM

**Pull request merged**
