### PR TITLE
Swaps current logo for a flatter design

### PR DESCRIPTION
**Pull request by McSherry**
Swaps the current D logo for a flatter design. Includes "normal" resolution (126x95), high resolution (3840x2880), and SVG (derived from high-res PNG).

New logo (isolated)

Logo comparison (new then old)

### CODE REVIEW

**Comment by CyberShadow** [comment]
Please see #853

**Comment by CyberShadow** [comment]
> New logo (isolated)

What is the purpose of the text on this image? Did a tool create it for you?

> and SVG (derived from high-res PNG).

You mean you took a SVG rendered as a PNG, edited it, and then vectorized it back to a 2337-line SVG?

**Comment by McSherry** [comment]
@CyberShadow: The text is just there to provide a quick note of colours/etc used in the image. It wasn't generated by a tool.

The SVG was created using a tracing tool on the high-res PNG.

**Comment by CyberShadow** [comment]
> The SVG was created using a tracing tool on the high-res PNG.

Rather wasteful, considering that the SVG of the current logo is available:

http://wiki.dlang.org/Art

**Comment by McSherry** [comment]
Using a tracing tool on the smaller PNG produced unsatisfactory results, and Inkscape (the tool used)'s  "Simplify" tool also produced unsatisfactory results.

**Comment by CyberShadow** [comment]
OK, not to nitpick but my point was that:

1. It might have been simpler to edit the original logo's SVG image
2. As your proposed logo is relatively simple, it would be relatively simple to recreate it by hand in an SVG editor

It is very silly that this image:

> 

is a 450KB (!) file, while its PNG counterpart is 2 KB.

**Comment by McSherry** [comment]
My apologies, I shouldn't have committed it. I've pushed a (much smaller) SVG.

**Comment by WalterBright** [comment]
I don't see a purpose to changing the logo.

**Comment by andralex** [comment]
The BDFL has spoketh. Sorry, will close this now.

**Pull request closed without merging**
