### PR TITLE
[dwarf] Remove documentation on outdated dwarf extensions

### PR DESCRIPTION
**Pull request by ibuclaw**
Complimentary to  https://github.com/D-Programming-Language/dmd/pull/4732

### CODE REVIEW

**Comment by JinShil** [comment]
http://dtest.thecybershadow.net/artifact/website-0e46c104c07b98c60b77c04788d52fa2df77cf55-53967985a6a4362b26872bb529a62d2c/dlangspec.html
Looks unstyled.  All other HTML looks fine.

**Comment by ibuclaw** [comment]
I don't see how that has anything to do with my changes. :)

**Comment by JinShil** [comment]
> http://dtest.thecybershadow.net/artifact/website-0e46c104c07b98c60b77c04788d52fa2df77cf55-53967985a6a4362b26872bb529a62d2c/dlangspec.html

Was intended for @CyberShadow.  There's not much to this PR, so the only thing that really needs checking is the DDoc and formatting.

> All other HTML looks fine.
I took a look at the DDoc and HTML generated as a result of your changes, and I didn't see any problems like missing parens etc...

Sorry if I'm making noise, I just want to try and get some of this stuff moved along.

**Comment by CyberShadow** [comment]
dlangspec.html is an intermediate file used for building the specfication ebook.

**Pull request merged**
