### PR TITLE
Issue 13302 - Inline ASM grammar is not left-associative

### PR DESCRIPTION
**Pull request by Hackerpilot**
https://issues.dlang.org/show_bug.cgi?id=13302

### CODE REVIEW

**Comment by Hackerpilot** [comment]
@WalterBright Does this seem reasonable?

**Comment by JinShil** [comment]
@WalterBright @yebblies @ibuclaw @klickverbot  It's an easy review.  Please take a look.

**Comment by Hackerpilot** [comment]
This lack of attention is why I can't fix the language spec.

**Comment by ibuclaw** [comment]
Seems reasonable.  Not something I implement though.

**Pull request merged**
