### PR TITLE
Issue 14661 - Add workaround for dpl-docs build failure

### PR DESCRIPTION
**Pull request by s-ludwig**

### CODE REVIEW

**Comment by CyberShadow** [comment]
Thanks. My understanding is that `dub --upgrade` will connect online and fetch the latest information about packages? If so, does this mean that a change in an online package will change Dub's behavior? (If possible, it would be ideal if we do not have dependencies on mutable external resources, as that makes things such as bisecting regressions very troublesome.)

**Comment by s-ludwig** [comment]
The `--missing-only` switch will cause it to download only what is already present in dub.selections.json, without looking for actual upgrade possibilities. Together with `dub build --nodeps` it basically just resembles the default behavior of `dub build` without `--nodeps`.

**Comment by CyberShadow** [comment]
Perfect, thanks. Testing now.

**Comment by CyberShadow** [comment]
Dub seems to be fixed!

Now I'm getting a PDF build error, but that's unrelated :)

**Comment by CyberShadow** [comment]
Testing the staging area now

**Comment by CyberShadow** [comment]
All fixed, yay!

**Comment by s-ludwig** [comment]
:+1:

**Pull request merged**
