### PR TITLE
Link to alpha mobile compiler releases

### PR DESCRIPTION
**Pull request by joakim-noah**
~~Only missing [the Android logo](https://commons.m.wikimedia.org/wiki/File:Android_robot.png), would appreciate if someone would process that image as needed and submit a PR with the Android logo.  I've used the openSUSE logo as a placeholder for now.~~ No logos needed anymore, much simpler.

### CODE REVIEW

**Comment by MartinNowak** [comment]
I wouldn't want to have those in our dmd release channels.
The download page is already too confusing, presenting visitors which a choice among dmd, ldc, and gdc.
Maybe under other downloads?

**Comment by CyberShadow** [comment]
Yes, other downloads please, and I don't think this warrants a table for 2 links.

**Comment by joakim-noah** [comment]
I like the way the current download page is done, presenting all three compilers and their differing strengths.  I don't see why a D compiler for mobile'd go under `Other downloads`, which aren't even D compilers.  However, I don't think it looked good the way I had it before, so I just moved it to the top, under the ldc banner.

**Comment by schuetzm** [comment]
I agree with @joakim-noah that it belongs in the LDC section. Is there still opposition against the updated proposal? IMO it looks nice.

**Comment by CyberShadow** [comment]
No oppositions here, just recommendations for improval. And yes, that looks nice to me, though I'd move it to the bottom line (after the Architectures line).

**Comment by joakim-noah** [comment]
Thanks, hopefully these alpha releases get more usage now and beaten into shape before merging upstream.

**Pull request merged**
